version: '3.0'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  postgresql-server:
    hostname: postgresql-server
    container_name: postgresql-server
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=coffee_user
      - POSTGRES_DB=coffee_db

  mongodb:
    hostname: mongodb-server
    container_name: mongodb-server
    image: mongo:4.4.17
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mujgan
      - MONGO_INITDB_ROOT_PASSWORD=bulduk
      - MONGO_INITDB_DATABASE=stockdb

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - '8085:8085'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mujgan
      - ME_CONFIG_MONGODB_ADMINPASSWORD=bulduk
      - ME_CONFIG_MONGODB_SERVER=mongodb-server



networks:
  default:
    driver: bridge