spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_db
    username: coffee_user
    password: 12345678
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8082
  error:
    include-message: always

